### ISSUE TITLE
Website revamp for OHBM and Beyond

### ISSUE THREAD

**Issue by jarmoza** [neurobagel/neurobagel.github.io#8]
Key points to address for website revamp:

On landing page
- [x] big figure of Neurobagel landscape (how does it all fit together) aka "Map of the Neurobagel ecosystem"
- [x] (re)draft section on "what do we do" -> base on poster mission statement
- [x] Each tool should have a high res screenshot and a brief section describing the tool

In the content section:
- [ ] add a new section for the CLI

Additional things to update
- [x] A funders section
- [x] Make a tag to denote core developers
- [x] Add more collaborators
  - Brent
  - Michelle
  - Remi
  - Yarik?
  - ...
- [x] Help us get a logo
- [x] How to get in touch / contribute
- [x] Form for user feedback (if available)

Related:
- [x] make a decision on whether to address in current website implementation or change to a different framework

## Steps:
- [x] Investigate if it makes sense for us to make all these changes directly using mkdocs with the overrides functionality: https://squidfunk.github.io/mkdocs-material/customization/#overriding-blocks
- [x] Make a decision on whether to put changes in mkdocs or to go with the HTML5Up template
- [x] Implement the changes

Things needed:

- [x] Screenshot for CLI - can also be a GIF
- [x] Three sentence description of CLI (Feature)
- [x] Nicer figure for "Look, open standards" Feature
- [x] Figure for the Graph + API -> "Look, so easy to deploy"
- [x] URL for place to "submit your logo idea here"

Resources: 
- https://github.com/up42/up42-py
- https://github.com/neurobagel/documentation/tree/landing_page
- https://github.com/neurobagel/documentation/issues/40

**Comment by jarmoza** [comment]
Given the proximity to OHBM our list of wants for the website revamp above should be divided into two groups: 

1. What we think has more priority and is feasible to do within the time before the conference, and
2. Enhancements for the "beyond" part, post-OHBM.

**Comment by surchs** [comment]
Link it to: https://github.com/neurobagel/documentation/issues/40

**Comment by surchs** [comment]
we will go with html5up

**Comment by alyssadai** [comment]
Link to logo submission form: https://form.jotform.com/231974699426069

**Comment by surchs** [comment]
Moving to blocked until https://github.com/neurobagel/documentation/issues/40 is resolved
